apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{name}"
  namespace: streamlit
  labels:
    app: "{name}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "{name}"
  template:
    metadata:
      labels:
        app: "{name}"
    spec:
      serviceAccountName: streamlit-serviceaccount
      containers:
      - name: git-sync
        image: registry.k8s.io/git-sync:v3.1.3
        volumeMounts:
          - name: code
            mountPath: /tmp/code
        env:
          - name: GIT_SYNC_REPO
            value: "{repo}"
          - name: GIT_SYNC_BRANCH
            value: "{branch}"
          - name: GIT_SYNC_ROOT
            value: /tmp/code
          - name: GIT_SYNC_DEST
            value: "repo"
          - name: GIT_KNOWN_HOSTS
            value: "false"
          - name: GIT_SYNC_WAIT
            value: "60"
      - name: streamlit
        image: python:3.9-slim
        env:
            - name: IN_HUB
              value: "True"
            - name: CODE_DIR
              value: "repo/{code_dir}"
            - name: ENTRYPOINT
              value: "main.py"
        command:
          - "/app/launch/launch.sh"
        ports:
        - containerPort: 80
        volumeMounts:
          - name: code
            mountPath: /app
          - name: launch
            mountPath: /app/launch
      volumes:
        - name: code
          emptyDir: {{ }}
        - name: launch
          configMap:
            name: streamlit-launch-script
            defaultMode: 0500