apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{name}"
  annotations:
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/target-type: 'ip'
    alb.ingress.kubernetes.io/listen-ports: '[{{"HTTP": 80}}, {{"HTTPS":443}}]'
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    #TODO: Handle this stuff in the templating or maybe a config map?
    alb.ingress.kubernetes.io/inbound-cidrs: <REPLACE ME>
    external-dns.alpha.kubernetes.io/hostname: "{name}-streamlit.<TEMPLATE-ME-WITH-HELM>"
    alb.ingress.kubernetes.io/certificate-arn: <FIGURE OUT IF THIS IS NEEDED>
  namespace: streamlit
spec:
  ingressClassName: alb
  rules:
    - host: "{name}-streamlit.<TEMPLATE-ME-WITH-HELM>"
      http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: "{name}"
                port:
                  number: 80