apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: streamlit-apps.fetch.com
spec:
  scope: Namespaced
  group: fetch.com
  names:
    kind: StreamlitApp
    plural: streamlit-apps
    singular: streamlit-app
    shortNames:
      - stapp
      - stapps
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              x-kubernetes-preserve-unknown-fields: true
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true