{{- if .Values.githubApp.enabled }}
{{- if .Values.githubApp.onePassword.enabled }}
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: github-app-credentials
  namespace: {{ .Release.Namespace }}
spec:
  itemPath: "vaults/{{ .Values.githubApp.onePassword.vault }}/items/{{ .Values.githubApp.onePassword.item }}"
  fields:
    - key: "app-id"
      secretKey: "App-Id"
    - key: "installation-id"
      secretKey: "Installation-Id"
    - key: "streamlit-operator.pem"
      secretKey: "streamlit-operator.pem"
      encoding: base64
  secretName: github-app-credentials
  secretType: "kubernetes.io/Opaque"
{{- end }}
{{- end }}