{{- if .Values.githubApp.enabled }}
{{- if .Values.githubApp.onePassword.enabled }}
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: github-app-credentials
  namespace: {{ .Release.Namespace }}
spec:
  itemPath: "vaults/{{ .Values.githubApp.onePassword.vault }}/items/{{ .Values.githubApp.onePassword.item }}"
{{- end }}
{{- end }}