apiVersion: v1
kind: ConfigMap
metadata:
  name: streamlit-operator-config
  namespace: streamlit
data:
  config.yaml: |
    baseDnsRecord: {{ .Values.baseDnsRecord }}
    ingressAnnotations: {{ .Values.ingressAnnotations }}