apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamlit-operator
  namespace: {{ .Release.Namespace }}
  labels:
    app: streamlit-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streamlit-operator
  template:
    metadata:
      labels:
        app: streamlit-operator
    spec:
      serviceAccountName: streamlit-serviceaccount
      
      initContainers:
        - name: git-sync
          image:  registry.k8s.io/git-sync/git-sync:v4.4.0
          env:
            - name: GITSYNC_REPO
              value: {{ .Values.githubApp.repoUrl | default "https://github.com/document-crunch/streamlit-operator.git" }}
            - name: GIT_SYNC_BRANCH
              value: {{ .Values.githubApp.branch | default "main" }}
            - name: GITSYNC_ROOT
              value: /tmp/code
            - name: GIT_SYNC_DEST
              value: "repo"
            - name: GIT_SYNC_ONE_TIME
              value: "true"
            - name: GIT_SYNC_SSH
              value: "false"
            - name: GIT_SYNC_KNOWN_HOSTS
              value: "false"
            # GitHub App authentication
            - name: GITSYNC_GITHUB_APP_APPLICATION_ID
              valueFrom:
                secretKeyRef:
                  name: github-app-credentials
                  key: App-Id
            - name: GITSYNC_GITHUB_APP_INSTALLATION_ID
              valueFrom:
                secretKeyRef:
                  name: github-app-credentials
                  key: Installation-Id
            - name: GITSYNC_GITHUB_APP_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: github-app-credentials
                  key: Private-Key
          volumeMounts:
            - name: code
              mountPath: /tmp/code
      containers:
      - name: streamlit-operator
        image: python:3.8.5
        env:
          - name: BASE_DNS_RECORD
            value: {{ required "Must provide a base dns to host your Streamlit apps" .Values.baseDnsRecord }}
          - name: NAMESPACE
            value: {{ .Release.Namespace }}
        ports:
        - containerPort: 80
        volumeMounts:
          - name: code
            mountPath: /app
          - name: config
            mountPath: "/config"
            readOnly: true
        workingDir: /app/repo/
        command: ["/app/repo/src/start.sh"]
      volumes:
        - name: code
          emptyDir: { }
        - name: config
          configMap:
            name: streamlit-operator-config
            items:
              - key: config.yaml
                path: config.yaml